name: Create Image

inputs:
  vm_file:
    required: true
  image_name:
    required: true
  image_tag:
    required: true

runs: 
  using: "composite"
  steps:
    - run: |
        IMAGE_TAG="${{inputs.image_tag}}"
        IMAGE_TAG=${IMAGE_TAG//\//\_}
        echo $IMAGE_TAG
        aws ecr get-login-password | docker login --username AWS --password-stdin 765814079306.dkr.ecr.us-east-1.amazonaws.com
        mkdir disk
        cp "${{inputs.vm_file}}" disk/"${{inputs.vm_file}}"
        docker build -t "${{inputs.image_name}}":"$IMAGE_TAG" .
        docker push "${{inputs.image_name}}":"$IMAGE_TAG"
      shell: bash
