name: Create Image

inputs:
  vm_file:
    required: true
  image_tag:
    required: true

runs: 
  using: "composite"
  steps:
    - run: |
      echo "${{inputs.image_tag}}"
      aws ecr get-login-password --region region | docker login --username AWS --password-stdin 765814079306.dkr.ecr.us-east-1.amazonaws.com
      rm -rvf disk; mkdir disk
      cp "${{inputs.vm_file}}" disk/"${{inputs.vm_file}}"
      docker build -t "${{inputs.image_tag}}" .
      docker push "${{inputs.image_tag}}"