---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "mixmode.fullname" . }}
spec:
  hosts:
    - "{{ include "mixmode.fullname" . }}.vp.bigbang.dev"
  gateways:
    - istio-system/public
  http:
    - route:
        - destination:
            host: {{ include "mixmode.fullname" . }}.mixmode.svc.cluster.local
            port:
              number: 443
