name: Fetch S3 Object

inputs:
  qcow2_file:
    required: true
  
runs:
  using: "composite"
  steps:
    - run: |
        virt-customize \
          -a "$QCOW2_FILE" \
          --run-command 'yum install -y cloud-init qemu-guest-agent' \
          --delete '/etc/cloud/cloud.cfg.d/99-installer.cfg' \
          --delete '/etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg' \
          --delete '/etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg' \
          --delete '/etc/netplan/*.yaml' \
          --delete '/etc/cloud/ds-identify.cfg'  \
          --run-command 'cloud-init clean --logs --seed'  \
          --delete '/var/lib/cloud/'  \
          --run-command 'sed -i '"'"'s/GRUB_CMDLINE_LINUX="\([^"]*\)"/GRUB_CMDLINE_LINUX="\1 console=tty0 console=ttyS0,115200n8"/'"'"' /etc/default/grub'  \
          --append-line '/etc/default/grub:GRUB_TERMINAL=serial' \
          --append-line '/etc/default/grub:GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"' \
          --run-command 'grub2-mkconfig -o /boot/grub2/grub.cfg'
      shell: bash
